### ISSUE TITLE
Problem while parsing description

### ISSUE THREAD

**Issue by dgtal** [DigitalBrands/booking-com-sdk#1]
Hello, how are you?

There's a problem parsing the hotel description.
`hotelier_welcome_message` isn't always present on the response.

For this reason, the description of the hotel isn't parsed.

I'm not 100% sure, but I think that `hotel_description` is always present when you you pass it in `extra` parameter.

So I think that a possible solution is change this:

```
$description = isset($hotelData['hotelier_welcome_message']) ? Description::fromArray($hotelData) : null;
```

for this:

```
$description = isset($hotelData['hotel_description']) ? Description::fromArray($hotelData) : null;
```

On the other hand, `fromArray` method of `Description` class must verify that the fields are present in the array.

```
    public static function fromArray(array $array): self
    {
        return new self(
            $array['hotelier_welcome_message'] ?? '',
            $array['hotel_important_information'] ?? '',
            $array['hotel_description'] ?? '',
            $array['license_number'] ?? ''
        );
    }
```

**Comment by aivchen** [comment]
Hello) 
Thanks for the report. I fixed hotelier_welcome_message - now it's optional.
But I didn't make all other fields (hotel_important_information, hotel_description, license_number) as optional.
If you can provide a hotel ID where some description fields are not present in API response I can fix them too.

For now you can use [v1.0.1-beta](https://github.com/DigitalBrands/booking-com-sdk/releases/tag/v1.0.1-beta) version

Thanks.

**Comment by dgtal** [comment]
Hello @Groonya 

Thanks for the fix.

I think you're right. The other fields are always present in the response.
I will let you know if I find a case where they're not present.

Best regards,
Rodrigo
